### ISSUE TITLE
Excuse generator

### ISSUE THREAD

**Issue by gummibjorn** [gummibjorn/dotahans#2]
[https://poyoarya.github.io/john](https://poyoarya.github.io/john) chli adaptiere

might check dota2 played ingame time of enemies

**Comment by tourn** [comment]
>might check dota2 played ingame time of enemies

This whole thing could profit from some analyses that run beforehand

* Which heroes played (we actually have that from the matchInfo, we just need a ID->name map somewhere)
* Play time
* Number of Buildings standing
* ... ?

Although we have to consider whether we want the excuse generator to actually analyze the game or whether we just want to generate random sentences for fun, i.e. some wacky sentences like "We only lost because their ancient bought a rapier" or "They only won because the secret shop has such a shitty strength gain"

**Comment by gummibjorn** [comment]
> Although we have to consider whether we want the excuse generator to actually analyze the game or whether we just want to generate random sentences for fun, i.e. some wacky sentences like "We only lost because their ancient bought a rapier" or "They only won because the secret shop has such a shitty strength gain"

if we have a good source for true random excuses i would go for that!

**Comment by tourn** [comment]
Done: 6984888f5d0dcb91fe33f99329ea8174fe914f8b
